#! /bin/bash

# This helper script launches the main python script of the config generator in a separate virtual environment.
# Any dependencies are automatically installed.
# The output of the script is saved to the current working directory.

set -e

OUTPUT="$(pwd)"

cd "$(dirname "$0")" || exit

# Create venv and install dependencies if it does not exist
if [ ! -f ".venv" ]
then
    python3 -m venv .venv
    # shellcheck source=/dev/null
    source .venv/bin/activate
    pip install -r requirements.txt
fi

# Activate venv (in case not active already)
# shellcheck source=/dev/null
source .venv/bin/activate

# Run the config builder
python3 src/main.py --output "$OUTPUT" "$@"
