#ifndef __EXA_COUETTE_CLASS_HEADER__
#define __EXA_COUETTE_CLASS_HEADER__

// This file is generated by the ExaHyPE toolkit.
// Please do not modify - it will be overwritten by the next
// ExaHyPE toolkit call.
// 
// ========================
//   www.exahype.eu
// ========================

#include <string>

#include "exahype/solvers/LimitingADERDGSolver.h"
#include "EXA_COUETTE_ADERDG.h"
#include "EXA_COUETTE_FV.h"

namespace couette{
  class EXA_COUETTE;
}

class couette::EXA_COUETTE: public exahype::solvers::LimitingADERDGSolver {  
  public:
    static constexpr int NumberOfVariables         = couette::AbstractEXA_COUETTE_ADERDG::NumberOfVariables;
    static constexpr int NumberOfParameters        = couette::AbstractEXA_COUETTE_ADERDG::NumberOfParameters;
    static constexpr int Order                     = couette::AbstractEXA_COUETTE_ADERDG::Order;
    static constexpr int NumberOfGlobalObservables = couette::AbstractEXA_COUETTE_ADERDG::NumberOfGlobalObservables;
    static constexpr int NumberOfDMPObservables    = couette::AbstractEXA_COUETTE_ADERDG::NumberOfDMPObservables;
    static constexpr int GhostLayerWidth           = couette::AbstractEXA_COUETTE_FV::GhostLayerWidth;
      
    EXA_COUETTE(
        const double maximumMeshSize,
        const int maximumMeshDepth,
        const int haloCells,
        const int regularisedFineGridLevels,
        const exahype::solvers::Solver::TimeStepping timeStepping,
        const int DMPObservables,
        const double DMPRelaxationParameter,
        const double DMPDifferenceScaling
);
    
    void projectOnFVLimiterSpace(const double* const luh, double* const lim) const override;
    void projectOnDGSpace(const double* const lim, double* const luh) const override;
    bool discreteMaximumPrincipleAndMinAndMaxSearch(const double* const luh, double* const boundaryMinPerVariables, double* const boundaryMaxPerVariables) override;
    void findCellLocalMinAndMax(const double* const luh, double* const localMinPerVariables, double* const localMaxPerVariable) override;
    void findCellLocalLimiterMinAndMax(const double* const lim, double* const localMinPerObservable, double* const localMaxPerObservable) override;
};

#endif // __EXA_COUETTE_CLASS_HEADER__