// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "VtkWriter_FV.h"

couette::VtkWriter_FV::VtkWriter_FV(couette::EXA_COUETTE& solver) {
  // @TODO Please insert your code here.
}

couette::VtkWriter_FV::~VtkWriter_FV() {
}

void couette::VtkWriter_FV::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void couette::VtkWriter_FV::finishPlotting() {
  // @TODO Please insert your code here.
}

void couette::VtkWriter_FV::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 5;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}