// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_VtkWriter_FV_CLASS_HEADER_
#define POSTPROCESSING_VtkWriter_FV_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace couette {
  class EXA_COUETTE;
  class VtkWriter_FV;
}

class couette::VtkWriter_FV : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  VtkWriter_FV(couette::EXA_COUETTE& solver);
  virtual ~VtkWriter_FV();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* const Q,
    double* const outputQuantities,
    double timeStamp) override;
};

#endif /* POSTPROCESSING_VtkWriter_FV_CLASS_HEADER_ */