// Copyright (C) 2015 Technische Universitaet Muenchen
// This file is part of the Mamico project. For conditions of distribution
// and use, please see the copyright notice in Mamico's main folder, or at
// www5.in.tum.de/mamico
#ifndef _MOLECULARDYNAMICS_SERVICES_RANDOMNUMBERSERVICE_H_
#define _MOLECULARDYNAMICS_SERVICES_RANDOMNUMBERSERVICE_H_

#include "tarch/la/Vector.h"
#include "tarch/TarchDefinitions.h"
#include <cstdlib>
#include <iostream>
#include <cmath>

namespace tarch {
  namespace utils {
    class RandomNumberService;
  }
}


/** creates random numbers.
 *  @author Philipp Neumann
 */
class tarch::utils::RandomNumberService {
  public:
    static RandomNumberService& getInstance();

    void init(bool fixSeed=false);

    void shutdown();

    /** returns a uniform random number distributed over the unit interval */
    double getUniformRandomNumber() const;

    /** returns a gaussian random number with zero mean and unit variance, generated by the Polar method */
    double getGaussianRandomNumber();

  private:
    RandomNumberService(){}
    ~RandomNumberService(){}

    tarch::la::Vector<2,double> _randomNumbers;

    bool _isFirstRandomNumber;
    bool _isInitialized{false};
};
#endif // _MOLECULARDYNAMICS_SERVICES_RANDOMNUMBERSERVICE_H_
