// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_Plotter_FV_CLASS_HEADER_
#define POSTPROCESSING_Plotter_FV_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"

namespace NavierStokes {
  class NavierStokesSolver_FV;
  class Plotter_FV;
}

class NavierStokes::Plotter_FV : public exahype::plotters::Plotter::UserOnTheFlyPostProcessing {
public:
  Plotter_FV(NavierStokes::NavierStokesSolver_FV& solver);
  virtual ~Plotter_FV();

  void startPlotting(double time) override;
  void finishPlotting() override;
  void mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp) override;
private:
    NavierStokesSolver_FV* solver;
};

#endif /* POSTPROCESSING_Plotter_FV_CLASS_HEADER_ */