// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "Plotter_Limiting.h"
#include "NavierStokesSolver.h"

NavierStokes::Plotter_Limiting::Plotter_Limiting(NavierStokes::NavierStokesSolver& solver) :
        Plotter(const_cast<NavierStokesSolver_ADERDG&>(
               static_cast<const NavierStokesSolver_ADERDG&>(*solver.getSolver()))) {
}
