// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
// ========================
//   www.exahype.eu
// ========================
#ifndef POSTPROCESSING_PlotterLimiting_CLASS_HEADER_
#define POSTPROCESSING_PlotterLimiting_CLASS_HEADER_

#include "exahype/plotters/Plotter.h"
#include "Plotter.h"

namespace NavierStokes {
  class NavierStokesSolver;
  class NavierStokesSolver_ADERDG;
  class Plotter_Limiting;
}

class NavierStokes::Plotter_Limiting : public NavierStokes::Plotter {
public:
  Plotter_Limiting(NavierStokes::NavierStokesSolver& solver);
};

#endif /* POSTPROCESSING_PlotterLimiting_CLASS_HEADER_ */