# This is the testing workflow

name: CTest

# Controls when the action will run. Triggers the workflow on push or pull request events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/hsu-hpc/testmamico

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Compiletest
      run: |
        mkdir build; cd build
        cmake -DCOMPILETEST_MODES=Release ..
        make compiletest

    - name: CMake
      run: cd build; cmake -DBUILD_TESTING=ON -DBUILD_WITH_MPI=ON .

    - name: Build
      run: cd build; make -j4 testmamico

    - name: Test
      run: cd build; ctest --output-on-failure
