# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Abort running jobs if a new one is triggered
concurrency:
  # github.ref = refs/heads/<branch_name> for push or refs/pull/<pr_number>/merge for pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # How to update container: See ../../test/docker/Readme.md
    container: ghcr.io/hsu-hpc/testmamico

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          # Path to Doxyfile
          doxyfile-path: "./Doxyfile" # default is ./Doxyfile
          # Working directory
          working-directory: "." # default is .
      - name: Doxygen Action
        if: github.event_name == 'push' # Only update documentation when PR was merged
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          # Path to Doxyfile
          doxyfile-path: "./Doxyfile" # default is ./Doxyfile
          # Working directory
          working-directory: "." # default is .
      - name: Get coverage
        run: |
          mkdir build
          cd build
          CXX=g++ cmake -DBUILD_WITH_MPI=ON -DCMAKE_BUILD_TYPE=Debug ..
          cmake -DBUILD_TESTING=ON -DENABLE_COVERAGE=ON .
          make -j2 testmamico
          ctest
          make coverage
          mkdir -p ../docs/html
          mv coverage ../docs/html/coverage
      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Default Doxyfile build documentation to html directory.
          # Change the directory if changes in Doxyfile
          publish_dir: ./docs/html

      # ========== Comment test coverage on corresponding PR ==========
      - name: Parse Coverage
        if: github.event_name == 'pull_request'
        id: "parse_coverage"
        run: |
          chown -R $(whoami):$(whoami) .. # Fix issue of reading files in repo
          echo 'PARSED_COVERAGE<<EOF' >> "$GITHUB_OUTPUT"
          python test/check_my_coverage.py | tee -a "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"
          COVERAGE_REACTION=$(grep "PARSED_COVERAGE=Sufficient" $GITHUB_OUTPUT -q && echo "rocket" || echo "eyes")
          echo "COVERAGE_REACTION=$COVERAGE_REACTION" >> "$GITHUB_OUTPUT"
          echo "debug output"
          cat $GITHUB_OUTPUT
          echo "debug grep"
          grep "PARSED_COVERAGE=Sufficient" $GITHUB_OUTPUT

      - name: Comment Test Coverage
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{steps.parse_coverage.outputs.PARSED_COVERAGE}}
          comment_tag: coverage
          mode: recreate
          reactions: ${{steps.parse_coverage.outputs.COVERAGE_REACTION}}
