name: Integration Testing

on:
  push:
    # TODO also on feature branch (just for testing)
    # branches:
    #   - master

jobs:
  extract-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: get-matrix
        name: Extract all test configurations from a text file
        run: |
          test/integration/gh-act/get-test-cases-matrix.py >> $GITHUB_OUTPUT

  build-executable:
    runs-on: minicluster
    strategy:
      fail-fast: false # If some versions fail to build, still build all the others
      matrix:
        md-solver: [md, ls1] # lammps (LAMMPS integration is currently broken -> issue #86)
    steps:
      - uses: actions/checkout@v4
      - name: Use cached LAMMPS/OpenFOAM
        uses: actions/cache/restore@v4
        with:
          path: |
            build/LAMMPS
            build/openfoam
          key: 3rd-party-solvers
      - name: Build couette executable
        # Add "--with-foam" for OpenFOAM support # (OpenFOAM integration is currently broken -> issue #73)
        run: |
          ml gcc mpi || :
          ./tools/build-couette.py \
            --jobs $(($(nproc --all) / 2)) \
            --with-mpi \
            --md-solver ${{ matrix.md-solver }}
      - name: Cache LAMMPS/OpenFOAM
        uses: actions/cache/save@v4
        with:
          path: |
            build/LAMMPS
            build/openfoam
          key: 3rd-party-solvers
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}-${{ runner.arch }}-${{ matrix.md-solver }}
          path: build

  run-tests:
    needs: [extract-tests, build-executable]
    if: "always()" # Only SOME couette binaries might have failed to build
    runs-on: minicluster
    strategy:
      matrix: ${{ fromJson(needs.extract-tests.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ runner.os }}-${{ runner.arch }}-${{ matrix.solver_md }}
          path: build
      - name: Generate the test configuration for ${{ matrix.case }}
        run: |
          MAMICO_CFG=$(pwd)/tools/mamico-cfg
          rm -rf build/test_cases # Clean up any old test
          mkdir -p build/test_cases/${{ matrix.case }} && cd $_
          O="domain_size=${{ matrix.domain_size }}"
          O="$O,use_checkpoint=${{ matrix.use_checkpoint }}"
          O="$O,solver_md=${{ matrix.solver_md }}"
          O="$O,solver_cfd=${{ matrix.solver_cfd }}"
          O="$O,mpi_ranks=${{ matrix.mpi_ranks }}"
          O="$O,cell_size=${{ matrix.cell_size }}"
          O="$O,boundary=${{ matrix.boundary }}"
          O="$O,coupling_2way=${{ matrix.coupling_2way }}"
          O="$O,filtering=${{ matrix.filtering }}"
          O="$O,simulation=${{ matrix.simulation }}"
          O="$O,multi_md=${{ matrix.multi_md }}"
          $MAMICO_CFG -O $O
      - run: alias && which srun && srun hostname # TODO remove (debug only)
      - name: Run the couette executable with the generated configuration
        run: cd build/test_cases/${{ matrix.case }} && srun -n ${{ matrix.mpi_ranks }} ../../couette
      - name: Assess couette profile
        run: ./tools/assess-couette-flow-profile.py build/test_cases/${{ matrix.case }}
      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.multi_md }}
          path: build/test_cases/${{ matrix.case }}
